env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
rules:
  {
    prettier/prettier: 0,
    consistent-return: 0,
    no-underscore-dangle: 0,
    no-unused-vars: ["error", { "argsIgnorePattern": "^_" }],
  }
