name: Deploy Action

on:
  push:
    branches:
      - production

env:
  DEPLOY_ENV: production
  GIT_BRANCH: production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          timeout: 600s
          proxy_timeout: 600s
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{vars.PROJECT_PATH}}

            git checkout production
            git reset --hard HEAD
            git pull

            yarn

            echo "${{secrets.ENV}}" >> .env

            chmod +x ${{vars.PROJECT_PATH}}/scripts/prod.sh
            ${{vars.PROJECT_PATH}}/scripts/prod.sh
